spring:
  application:
    name: PokemonApp
  datasource:
    url: jdbc:postgresql://localhost:5432/pokemon_app
    username: postgres
    password: 1234
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    hibernate:
      dialect: org.hibernate.dialect.PostgreSQLDialect
      ddl-auto: update
      jdbc:
        lob:
          non-contextual-creation:


pokemon:
  api:
    url: https://pokeapi.co/api/v2

pokemon_app:
  jwt:
    secret: my-secure-secret-key-for-authentication-of-spring-project!
    expiration: 86400000

server:
  port: 18081

